# Generated by Django 5.2.15 on 2026-06-04 01:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='휴대폰')),
                ('role', models.CharField(choices=[('ADMIN', '관리자'), ('COUNSELOR', '상담사'), ('CLIENT', '내담자')], default='CLIENT', max_length=20, verbose_name='역할')),
                ('status', models.CharField(choices=[('PENDING', '승인대기'), ('ACTIVE', '활성'), ('INACTIVE', '비활성'), ('SUSPENDED', '정지')], default='PENDING', max_length=20, verbose_name='상태')),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='행동')),
                ('target_type', models.CharField(blank=True, max_length=100, verbose_name='대상 유형')),
                ('target_id', models.UUIDField(blank=True, null=True, verbose_name='대상 ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='일시')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '감사 로그',
                'verbose_name_plural': '감사 로그',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('gender', models.CharField(blank=True, max_length=10, verbose_name='성별')),
                ('emergency_contact', models.JSONField(blank=True, default=dict, verbose_name='비상연락처')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '내담자 프로필',
                'verbose_name_plural': '내담자 프로필',
            },
        ),
        migrations.CreateModel(
            name='CounselorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='자격증 번호')),
                ('specialties', models.JSONField(blank=True, default=list, verbose_name='전문분야')),
                ('bio', models.TextField(blank=True, verbose_name='소개')),
                ('max_cases', models.PositiveIntegerField(default=10, verbose_name='최대 동시 사례 수')),
                ('is_approved', models.BooleanField(default=False, verbose_name='승인 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '상담사 프로필',
                'verbose_name_plural': '상담사 프로필',
            },
        ),
    ]
