# Generated by Django 5.2.15 on 2026-06-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clientprofile_emergency_contact_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20, verbose_name='비상연락처'),
        ),
    ]
