# Generated by Django 5.2.15 on 2026-06-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='student_id',
            field=models.CharField(blank=True, help_text='회원가입·상담 신청 시 확정되며, 내담자 회원정보 수정 화면에서는 변경할 수 없습니다.', max_length=20, verbose_name='학번'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='회원가입 시 확정되며, 내담자 회원정보 수정 화면에서는 변경할 수 없습니다.', max_length=100, verbose_name='이름'),
        ),
    ]
