# Generated by Django 5.2.15 on 2026-06-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_counselorprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='department',
            field=models.CharField(blank=True, help_text='숭실사이버대학교 학생인 경우 회원가입 시 입력합니다.', max_length=100, verbose_name='소속 학과'),
        ),
    ]
