# Generated by Django 5.2.15 on 2026-07-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_supervisor_role_and_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='내담자 내정보에서 수정할 수 있습니다.', null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='student_id',
            field=models.CharField(blank=True, help_text='선택 사항. 내담자 내정보에서 수정할 수 있습니다.', max_length=20, verbose_name='학번'),
        ),
    ]
