# Generated by Django 5.2.15 on 2026-06-04 01:21

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counseling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosureReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(verbose_name='개입 요약')),
                ('outcomes', models.TextField(verbose_name='성과')),
                ('recommendations', models.TextField(blank=True, verbose_name='추후 권고')),
                ('closure_reason', models.CharField(max_length=200, verbose_name='종결 사유')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일')),
                ('pdf_file', models.FileField(blank=True, upload_to=apps.documents.models.closure_report_upload_path, verbose_name='PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closure_report', to='counseling.case', verbose_name='사례')),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_reports', to=settings.AUTH_USER_MODEL, verbose_name='상담사')),
            ],
            options={
                'verbose_name': '종결보고서',
                'verbose_name_plural': '종결보고서',
            },
        ),
        migrations.CreateModel(
            name='ConsentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('PRIVACY', '개인정보 동의'), ('COUNSELING', '상담 동의'), ('RECORDING', '녹화 동의')], max_length=20, verbose_name='동의서 유형')),
                ('file', models.FileField(upload_to=apps.documents.models.consent_upload_path, verbose_name='파일')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='서명일')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_documents', to='counseling.counselingapplication', verbose_name='상담 신청')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_documents', to=settings.AUTH_USER_MODEL, verbose_name='내담자')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_consents', to=settings.AUTH_USER_MODEL, verbose_name='검증자')),
            ],
            options={
                'verbose_name': '동의서',
                'verbose_name_plural': '동의서',
                'unique_together': {('application', 'doc_type')},
            },
        ),
    ]
