# Generated by Django 5.2.15 on 2026-06-08 11:00

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0018_split_complaint_fields'),
        ('documents', '0005_sessionmaterial_board_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorAssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_number', models.PositiveIntegerField(blank=True, help_text='특정 회기와 연관된 과제인 경우 선택합니다.', null=True, verbose_name='회차')),
                ('title', models.CharField(max_length=200, verbose_name='과제명')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('file', models.FileField(upload_to=apps.documents.models.counselor_assignment_upload_path, verbose_name='파일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='제출일')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_assignments', to='counseling.case', verbose_name='사례')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_assignment_submissions', to=settings.AUTH_USER_MODEL, verbose_name='제출 상담사')),
            ],
            options={
                'verbose_name': '상담사 과제 제출',
                'verbose_name_plural': '상담사 과제 제출',
                'ordering': ['-created_at'],
            },
        ),
    ]
