# Generated by Django 5.2.15 on 2026-06-15 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_counselorassignmentsubmission_cohort'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CounselorAssignmentSubmission',
        ),
    ]
