# Generated by Django 5.2.15 on 2026-06-26 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_remove_counselor_assignment_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consentdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='최종 수정일'),
        ),
        migrations.AddField(
            model_name='consentdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_consent_documents', to=settings.AUTH_USER_MODEL, verbose_name='업로드한 사용자'),
        ),
        migrations.AlterField(
            model_name='consentdocument',
            name='doc_type',
            field=models.CharField(choices=[('PRIVACY', '개인정보 처리방침 동의서'), ('INTAKE', '접수면접지'), ('COUNSELING', '상담 동의서'), ('RECORDING', '녹화 동의')], max_length=20, verbose_name='동의서 유형'),
        ),
    ]
