# Generated by Django 5.2.15 on 2026-06-26

from django.db import migrations, models

import apps.documents.models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0010_consent_counselor_upload_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consentdocument",
            name="file",
            field=models.FileField(
                upload_to=apps.documents.models.consent_upload_path,
                verbose_name="파일",
            ),
        ),
    ]
