# Generated by Django 5.2.15 on 2026-07-01 04:18

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_consentdocument_storage_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentdocument',
            name='file',
            field=models.FileField(storage=apps.documents.models._consent_file_storage, upload_to=apps.documents.models.consent_upload_path, verbose_name='파일'),
        ),
    ]
