# Generated by Django 5.2.15 on 2026-06-04 01:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('counseling_type', models.CharField(max_length=50, verbose_name='상담 유형')),
                ('reason', models.TextField(verbose_name='상담 사유')),
                ('urgency', models.CharField(choices=[('NORMAL', '일반'), ('URGENT', '긴급')], default='NORMAL', max_length=20, verbose_name='긴급도')),
                ('preferred_schedule', models.JSONField(blank=True, default=dict, verbose_name='희망 일정')),
                ('status', models.CharField(choices=[('RECEIVED', '접수'), ('WAITING_MATCH', '매칭대기'), ('MATCHED', '매칭완료'), ('IN_PROGRESS', '진행중'), ('CLOSED', '종결'), ('CANCELLED', '취소')], default='RECEIVED', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='신청일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='내담자')),
            ],
            options={
                'verbose_name': '상담 신청',
                'verbose_name_plural': '상담 신청',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=20, unique=True, verbose_name='사례번호')),
                ('status', models.CharField(choices=[('ACTIVE', '개입중'), ('ON_HOLD', '휴지'), ('CLOSED', '종결'), ('TRANSFERRED', '이관')], default='ACTIVE', max_length=20, verbose_name='상태')),
                ('risk_level', models.CharField(choices=[('LOW', '낮음'), ('MEDIUM', '보통'), ('HIGH', '높음')], default='LOW', max_length=20, verbose_name='위험도')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='태그')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='개시일')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='종결일')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_cases', to=settings.AUTH_USER_MODEL, verbose_name='내담자')),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselor_cases', to=settings.AUTH_USER_MODEL, verbose_name='상담사')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='counseling.counselingapplication', verbose_name='상담 신청')),
            ],
            options={
                'verbose_name': '사례',
                'verbose_name_plural': '사례',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddIndex(
            model_name='counselingapplication',
            index=models.Index(fields=['status', 'created_at'], name='counseling__status_018fcd_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['counselor', 'status'], name='counseling__counsel_502aa6_idx'),
        ),
    ]
