# Generated by Django 5.2.15 on 2026-06-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0002_case_zoom_meeting_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselingapplication',
            name='status',
            field=models.CharField(choices=[('RECEIVED', '접수'), ('WAITING_MATCH', '매칭대기'), ('MATCHED', '매칭완료'), ('IN_PROGRESS', '진행중'), ('CLOSED', '종결'), ('CANCELLED', '취소')], default='WAITING_MATCH', max_length=20, verbose_name='상태'),
        ),
    ]
