# Generated by Django 5.2.15 on 2026-06-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0009_counselingapplication_counseling_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselingapplication',
            name='reason',
            field=models.TextField(verbose_name='주요 호소 문제'),
        ),
    ]
