# Generated by Django 5.2.15 on 2026-06-11 06:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0020_case_counseling_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=2000, verbose_name='메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='보낸 시간')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='counseling.case', verbose_name='사례')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='받는 사람')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='보낸 사람')),
            ],
            options={
                'verbose_name': '채팅 메시지',
                'verbose_name_plural': '채팅 메시지',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['case', 'created_at'], name='counseling__case_id_a434bc_idx')],
            },
        ),
    ]
