# Generated by Django 5.2.15 on 2026-06-11 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0021_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='읽음'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['case', 'recipient', 'is_read'], name='counseling__case_id_9af639_idx'),
        ),
    ]
