# Generated by Django 5.2.15 on 2026-07-01 07:02

import apps.counseling.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0053_reassign_zoom_hosts_with_buffer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasePresentationPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cohort', models.PositiveIntegerField(db_index=True, verbose_name='기수')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('file', models.FileField(upload_to=apps.counseling.models._presentation_post_upload_path, verbose_name='첨부 파일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_presentation_posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '사례발표 게시글',
                'verbose_name_plural': '사례발표 게시글',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CasePresentationComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('file', models.FileField(upload_to=apps.counseling.models._presentation_comment_upload_path, verbose_name='첨부 파일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_presentation_comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='counseling.casepresentationpost', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '사례발표 댓글',
                'verbose_name_plural': '사례발표 댓글',
                'ordering': ['created_at'],
            },
        ),
    ]
