# Generated by Django 5.2.15 on 2026-07-01 07:46

import apps.counseling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0054_case_presentation_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casepresentationcomment',
            name='file',
            field=models.FileField(blank=True, upload_to=apps.counseling.models._presentation_comment_upload_path, verbose_name='첨부 파일'),
        ),
    ]
