# Generated by Django 5.2.15 on 2026-07-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0055_optional_presentation_comment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='casepresentationcomment',
            name='file_password_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name='파일 다운로드 암호 해시'),
        ),
        migrations.AddField(
            model_name='casepresentationpost',
            name='file_password_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name='파일 다운로드 암호 해시'),
        ),
    ]
