# Generated by Django 5.2.15 on 2026-09-01 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0058_clear_auto_backfilled_presentation_passwords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='records_submitted_at',
            field=models.DateTimeField(blank=True, help_text='상담사가 상담일지·종결기록지를 최종 제출한 시각. 값이 있으면 기록이 잠깁니다.', null=True, verbose_name='기록 최종 제출일'),
        ),
        migrations.AddField(
            model_name='case',
            name='records_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_cases', to=settings.AUTH_USER_MODEL, verbose_name='기록 최종 제출자'),
        ),
    ]
