# Generated by Django 5.2.15 on 2026-06-04 01:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counseling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(help_text='0=월요일, 6=일요일', verbose_name='요일')),
                ('start_time', models.TimeField(verbose_name='시작 시간')),
                ('end_time', models.TimeField(verbose_name='종료 시간')),
                ('slot_duration', models.PositiveIntegerField(default=50, verbose_name='슬롯 시간(분)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL, verbose_name='상담사')),
            ],
            options={
                'verbose_name': '상담 가능 시간',
                'verbose_name_plural': '상담 가능 시간',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField(verbose_name='예약 일시')),
                ('duration_minutes', models.PositiveIntegerField(default=50, verbose_name='상담 시간(분)')),
                ('status', models.CharField(choices=[('SCHEDULED', '예약'), ('CONFIRMED', '확정'), ('COMPLETED', '완료'), ('CANCELLED', '취소'), ('NO_SHOW', '노쇼')], default='SCHEDULED', max_length=20, verbose_name='상태')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='취소일')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='취소 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='counseling.case', verbose_name='사례')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to=settings.AUTH_USER_MODEL, verbose_name='내담자')),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_appointments', to=settings.AUTH_USER_MODEL, verbose_name='상담사')),
            ],
            options={
                'verbose_name': '예약',
                'verbose_name_plural': '예약',
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['counselor', 'scheduled_at'], name='scheduling__counsel_70eb8d_idx')],
                'constraints': [models.UniqueConstraint(fields=('counselor', 'scheduled_at'), name='unique_counselor_scheduled_at')],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='날짜')),
                ('is_available', models.BooleanField(default=False, help_text='False=휴무', verbose_name='가능 여부')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='메모')),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to=settings.AUTH_USER_MODEL, verbose_name='상담사')),
            ],
            options={
                'verbose_name': '일정 예외',
                'verbose_name_plural': '일정 예외',
                'unique_together': {('counselor', 'date')},
            },
        ),
    ]
