# Generated by Django 5.2.15 on 2026-06-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_appointment_session_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='request_message',
            field=models.TextField(blank=True, help_text='회기별 예약·일정 변경 요청 시 내담자가 입력한 내용', verbose_name='예약 요청 내용'),
        ),
    ]
