# Generated by Django 5.2.15 on 2026-06-04 01:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counseling', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zoom_meeting_id', models.CharField(max_length=100, verbose_name='Zoom Meeting ID')),
                ('join_url', models.URLField(verbose_name='참가 URL')),
                ('start_url', models.URLField(blank=True, verbose_name='호스트 URL')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='비밀번호')),
                ('recording_url', models.URLField(blank=True, verbose_name='녹화 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_meeting', to='scheduling.appointment', verbose_name='예약')),
            ],
            options={
                'verbose_name': 'Zoom 미팅',
                'verbose_name_plural': 'Zoom 미팅',
            },
        ),
        migrations.CreateModel(
            name='CounselingJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_number', models.PositiveIntegerField(verbose_name='회차')),
                ('subjective', models.TextField(blank=True, verbose_name='S (주관적)')),
                ('objective', models.TextField(blank=True, verbose_name='O (객관적)')),
                ('assessment', models.TextField(blank=True, verbose_name='A (평가)')),
                ('plan', models.TextField(blank=True, verbose_name='P (계획)')),
                ('is_draft', models.BooleanField(default=True, verbose_name='임시저장')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals', to='scheduling.appointment', verbose_name='예약')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='counseling.case', verbose_name='사례')),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL, verbose_name='상담사')),
            ],
            options={
                'verbose_name': '상담일지',
                'verbose_name_plural': '상담일지',
                'ordering': ['case', 'session_number'],
                'indexes': [models.Index(fields=['case', 'session_number'], name='sessions_ap_case_id_d3fbba_idx')],
                'unique_together': {('case', 'session_number')},
            },
        ),
    ]
