# Generated by Django 5.2.15 on 2026-06-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0002_counselingjournal_session_consumed'),
        ('sessions_app', '0002_counselingjournal_session_fields'),
    ]

    operations = [
    ]
