# Generated by Django 5.2.15 on 2026-06-08 09:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0011_alter_case_zoom_meeting_url'),
        ('sessions_app', '0005_initialcounselingrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminationCounselingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('counseling_period', models.TextField(blank=True, verbose_name='상담 진행 일시')),
                ('main_topics', models.TextField(blank=True, verbose_name='상담받은 주요주제')),
                ('termination_reason', models.TextField(blank=True, verbose_name='종결(중단) 사유')),
                ('counselor_opinion', models.TextField(blank=True, verbose_name='내담자에 대한 상담자 소견')),
                ('post_termination_plan', models.TextField(blank=True, verbose_name='종결 후 계획 또는 후속조치')),
                ('other_notes', models.TextField(blank=True, verbose_name='기타')),
                ('is_draft', models.BooleanField(default=True, verbose_name='임시저장')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='termination_counseling_record', to='counseling.case', verbose_name='사례')),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termination_counseling_records', to=settings.AUTH_USER_MODEL, verbose_name='상담사')),
            ],
            options={
                'verbose_name': '종결기록지',
                'verbose_name_plural': '종결기록지',
            },
        ),
    ]
